import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Shop | Illustrando ad occhi chiusi",
    description: "Generated by create next app",
    keywords: "illustrazione, illustrando, ritratto, shop, bendedetta",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

    return (
        <>
         {children}
        </>
    );
}