import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const roboto = Roboto({
  weight:["400","500","600","700"],
  style:["normal","italic"],
  subsets:["latin","latin-ext"],
}) 


export const metadata: Metadata = {
  title: "Illustrando ad occhi chiusi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <header>
          <Navbar />
        </header>
        <main className="mt-40 h-auto">
          {children}
          <Toaster />
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
